### ISSUE TITLE
Object.setPrototypeOf(foo, null) crashes

### ISSUE THREAD

**Issue by cpcallen** [NeilFraser/CodeCity#181]
`Object.setPrototypeOf` crashes when given `null` as second parameter:

```
> Object.setPrototypeOf({}, null);

TypeError: Cannot read property 'properties' of null
    at intrp.Object.setPrototypeOf (/Users/cpcallen/src/CodeCity/server/interpreter.js:3998:50)
    at intrp.NativeFunction.call (/Users/cpcallen/src/CodeCity/server/interpreter.js:732:18)
    at Interpreter.stepFuncs_.Call (/Users/cpcallen/src/CodeCity/server/interpreter.js:5659:14)
    at Interpreter.stepFuncs_.CallExpression (/Users/cpcallen/src/CodeCity/server/interpreter.js:5622:29)
    at Interpreter.run (/Users/cpcallen/src/CodeCity/server/interpreter.js:309:38)
```

**Comment by cpcallen** [comment]
Fixed by 5a9312a.
